require:
  - rubocop-rails

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'db/migrate/**/*'
    - 'test/**/*'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/environments/development.rb'

AllCops:
  SuggestExtensions: false
