# Resources:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-ruby#specifying-the-ruby-version

name: linting
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1 # https://github.com/ruby/setup-ruby
        with:
          bundler-cache: true
          # ruby-version: '3.3.4' # Not needed with a .ruby-version file
d
      - name: Run rubocop
        run: bundle exec rubocop --parallel

      # - name: Run erb-lint
      #   run: bundle exec erblint --lint-all