# Resources:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-ruby#specifying-the-ruby-version

name: linting
on: [pull_request]

jobs:
  lint:
    name: rubocop
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1 # https://github.com/ruby/setup-ruby
        with:
          bundler-cache: true
          # ruby-version: '3.3.4' # Not needed with a .ruby-version file
      - name: rubocop
        run: bundle exec rubocop --parallel
      # - name: erb-lint
      #   run: bundle exec erblint --lint-all